cache:
  key: "$CI_BUILD_REF"
  paths:
    - DisableTracking/

stages:
  - build
  - test
  - archive

build:
  stage: build
  tags:
    - php
  script:
    - rm -rf DisableTracking
    - mv src DisableTracking

archive:
  stage: archive
  tags:
    - php
  script:
    - sed -i "s/\"version\"`echo \":\"` \"master\",/\"version\"`echo \":\"` \"$CI_BUILD_REF_NAME\",/g" DisableTracking/plugin.json
    - sed -i "s/\"version\"`echo \":\"` \"0.0.0\",/\"version\"`echo \":\"` \"$CI_BUILD_REF_NAME\",/g" DisableTracking/plugin.json
  artifacts:
    name: DisableTracking-$CI_BUILD_REF_NAME
    paths:
      - DisableTracking/
  only:
    - master
    - tags